version: "3.3"
services:
  facebook-clone-frontend:
    image: saykot/facebook-clone-frontend:1.0.0
    ports:
      - "3000:3000"
    depends_on:
      - facebook-clone-backend
      - mongo
  facebook-clone-backend:
    image: saykot/facebook-clone-backend:1.0.1
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - EMAIL=<email>
      - EMAIL_PASSWORD=<password>
      - TOKENSECRATE=<secrate>
      - DATABASE_URL=<mongodbURL>
      - CLIENT_URL=http://localhost:3000
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
    driver: local
