apiVersion: apps/v1
kind: Deployment
metadata:
  name: facebook-backend-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: facebook-backend
  template:
    metadata:
      labels:
        app: facebook-backend
    spec:
      containers:
        - name: facebook-backend
          image: saykot/facebook-clone-backend:1.0.1
          ports:
            - containerPort: 8000
          env:
            - name: TOKENSECRATE
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: token-secrate
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: database-url
            - name: EMAIL
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: email
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: email-password
            - name: CLIENT_URL
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: cliet-url
          volumeMounts:
            - name: server-storage
              mountPath: ./uploads
      volumes:
        - name: server-storage
          persistentVolumeClaim:
            claimName: server-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: facebook-backend-srv
spec:
  selector:
    app: facebook-backend
  ports:
    - port: 8000
      targetPort: 8000
